budimanpranata/mysys

resources/views/admin/index.blade.php

udah view index, hapus 'Admin'

udah view index, hapus 'Admin'

---

database/migrations/2024_10_09_015039_create_anggotas_table.php
database/seeders/AnggotaSeeder.php

add seeder anggota

---

app/Models/Mm.php
database/migrations/2025_01_13_040758_create_temp_akad_muses_table.php
database/migrations/2025_01_20_064832_create_mm_table.php
database/seeders/DatabaseSeeder.php
database/seeders/MmSeeder.php
database/seeders/kelompok.php
database/seeders/tempAkadMus.php

add migrasi table mm, seeder data mm, tambah field persen margin

add migrasi table mm, seeder data mm, tambah field persen margin

---

app/Http/Controllers/CetakCsWoController.php
app/Models/Kelompok.php
app/Models/branch.php
composer.json
composer.lock
config/datatables.php
database/migrations/2025_01_22_010651_create_branches_table.php
database/seeders/DatabaseSeeder.php
resources/views/admin/cetak_cs_wo/framePdf.blade.php
resources/views/admin/cetak_cs_wo/index.blade.php
resources/views/admin/cetak_cs_wo/pdfcs.blade.php
resources/views/admin/cetak_larisywah/index.blade.php
resources/views/layouts/main.blade.php
routes/web.php

Perbaikan model kelompok,
install depedency yajra
cetak cs WO, tabel wo belum terbentuk karena harus melalui proses WO. untuk sementara menggunakan tabel pembiayaan.

CS WO perbaikan Model kelomok dan depedency yajra

---

app/Http/Controllers/CetakApprovalController.php
app/Http/Controllers/CetakLaRisywahController.php
app/Http/Controllers/PDFController.php
database/seeders/MenuSeeder.php
database/seeders/RekomendasiSeeder.php
database/seeders/tempAkadMus.php
resources/views/admin/cetak_approval/index.blade.php
resources/views/admin/cetak_approval/results.blade.php
resources/views/admin/cetak_approval/template.blade.php
resources/views/admin/cetak_larisywah/index.blade.php
routes/web.php

penyelesaian cetak approval dan revisi untuk cetak la risywah dan mus…

penyelesaian cetak approva

---

database/migrations/2025_02_24_132939_create_tabel_transaksi_table.php
database/migrations/2025_02_24_132957_create_jurnal_umum_table.php
database/migrations/2025_02_24_133004_create_jurnal_masuk_table.php
database/migrations/2025_02_24_133034_create_pembiayaan_detail_table.php
database/seeders/JurnalMasukSeeder.php
database/seeders/JurnalUmumSeeder.php
database/seeders/PembiayaanDetailSeeder.php
database/seeders/TabelTransaksiSeeder.php

menambahkan table transaksi
jurnal umum
jurnal masuk
tabel transaksi
pembiayaan detail

add table transaksi

---

app/Http/Controllers/RestKemampuanBayarController.php
app/Http/Controllers/SetoranLimaPersenController.php
app/Models/pembiayaan.php
database/migrations/2025_02_12_045506_create_history_rest_table.php
database/seeders/MenuSeeder.php
resources/views/admin/master_anggota/form.blade.php
resources/views/admin/rest_kemampuan_bayar/index.blade.php
resources/views/layouts/main.blade.php
routes/web.php

1. Ada peruahan pada main bagian disable jquery-3.6.0.min.js .  tidak lagi ambil dari repo namun di ambil dari bawaan boostrap. sesuai template sebebelumnya.
{{-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> --}}
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
2. pada anggota kolom NIK remove readonly
3. Model pembiayaan  premary key jadi CIF, sebelumnya no_anggota disesuaikan dengan strutur tabel pembiaayan CIF Key nya.
4. Ada perubahan tipe data Schema histroy rest file jatpo_baru.

Rest Kemampuan Bayar

---

app/Http/Controllers/RealisasiMusyarokahController.php
app/Models/MusyarokahDetail.php
database/migrations/2025_01_06_061240_create_param_libur.php
database/migrations/2025_02_24_132939_create_tabel_transaksi_table.php
database/migrations/2025_04_30_020343_create_musyarokah_details_table.php
database/seeders/DatabaseSeeder.php
database/seeders/MenuSeeder.php
database/seeders/paramLiburSeder.php
resources/views/admin/realisasi_musyarokah/index.blade.php
routes/web.php

Proses Realisasi Musyarokah terdapat penambahan seeder pada parameter libur.

Proses Realisasi Musyarakah

---

database/seeders/MenuSeeder.php
resources/views/admin/master_anggota/create.blade.php
routes/web.php

perbaikan route pada menu view data dan master anggota
penyesuaian route pada view data dan master anggota

perbaikan routing view_data dan master_anggota

---

resources/views/layouts/sidebar.blade.php

menambahkan logo ni pada sidebar

tambah logo ni pada sidebar

---

app/Http/Controllers/PembiayaanController.php
resources/views/admin/master_pembiayaan/edit.blade.php

popup modal
tenor validation
set locale for day names

minor addition

---

app/Http/Controllers/SetoranBedaHariController.php
database/seeders/MenuSeeder.php
resources/views/admin/setoran_beda_hari/index.blade copy.php
resources/views/admin/setoran_beda_hari/index.blade.php
routes/web.php

Setoran beda hari

---

app/Http/Controllers/PemindahbukuanPerkelompokController.php
database/seeders/MenuSeeder.php
resources/views/admin/pemindahbukuan_perkelompok/index.blade.php
routes/web.php

Pemindahbukuan perkelompok

---

database/migrations/2025_06_24_042120_create_tabel_master_table.php
database/seeders/TabelMasterSeeder.php

Seeder table master

---

app/Http/Controllers/JurnalUmumController.php
database/seeders/MenuSeeder.php
resources/views/admin/jurnal_umum/cetak_pdf.blade.php
resources/views/admin/jurnal_umum/index.blade.php
routes/web.php

Jurnal umum

---

app/Http/Controllers/JurnalKeluarController.php
database/seeders/MenuSeeder.php
resources/views/admin/jurnal_keluar/index.blade.php
routes/web.php

Jurnal keluar

---

app/Exports/ListJurnalExport.php
app/Http/Controllers/ListJurnalController.php
database/seeders/MenuSeeder.php
resources/views/admin/list_jurnal/export.blade.php
resources/views/admin/list_jurnal/index.blade.php
routes/web.php

list jurnal

---

app/Http/Controllers/MutasiKasController.php
database/seeders/MenuSeeder.php
resources/views/admin/mutasi_kas/index.blade.php
routes/web.php

mutasi kas

---

app/Exports/PembiayaanExport.php
app/Http/Controllers/ReportNominativePembiayaanController.php
database/seeders/MenuSeeder.php
resources/views/admin/report_nominative_pembiayaan/index.blade.php
routes/web.php

Report nominative pembiayaan

---

database/migrations/2025_01_20_111913_create_simpanans_table.php
database/migrations/2025_01_20_231718_create_simpanan_pokoks_table.php
database/migrations/2025_01_20_231737_create_simpanan_wajibs_table.php
database/migrations/2025_01_21_010342_create_tunggakans_table.php
database/migrations/2025_02_24_132939_create_tabel_transaksi_table.php

migrations - perbaikan type data table

migrations - perbaikan type data

---

app/Http/Controllers/JurnalUmumController.php
resources/views/admin/jurnal_umum/cetak_pdf.blade.php

Jurnal Umum - Perbaikan Cetak PDF

Jurnal Umum - Perbaikan Cetak PDF
